### PR TITLE
Update dependencies and fix deprecations

### PR DESCRIPTION
**Pull request by romulomachado**
- [x] Ran `ember init` and upgraded all dependencies;
- [x] Fixed two deprecation warnings
  - [x] DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead.
  - [x] DEPRECATION: Overriding init without calling this._super is deprecated.

### CODE REVIEW

**Comment by romulomachado** [comment]
@brenna Same thing as ember-ted-shed#3 here. Need help testing it because I'm not sure how to test it. Suite is passing, but it's not very useful atm.

**Comment by romulomachado** [comment]
Once this is accepted, I have a PR for `ember-cli-deploy-front-end-builds-pack` as well. :wink:

**Comment by brenna** [comment]
@romulomachado I'm not sure how to test this programatically either, as I didn't author any of it. My best guess is to spot check by installing it on a fresh ember repo or upgrading an existing project and ensure deploys work as expected.

**Comment by kiwi-josh** [comment]
Any movement on this one?

**Pull request closed without merging**
